#!/usr/bin/env bash
# Refresh everything that depends on Cloudflare's published IP ranges:
#   1. /etc/nginx/snippets/cloudflare-realip.conf  (restores the visitor IP in logs)
#   2. ufw rules allowing :443 only from those ranges
# Safe to re-run; bootstrap.sh installs a weekly systemd timer that does.
set -euo pipefail

V4=$(curl -fsS https://www.cloudflare.com/ips-v4)
V6=$(curl -fsS https://www.cloudflare.com/ips-v6)
[ -n "$V4" ] && [ -n "$V6" ] || { echo "empty IP list from cloudflare.com; leaving config unchanged" >&2; exit 1; }

out=/etc/nginx/snippets/cloudflare-realip.conf
tmp=$(mktemp)
{
  echo "# Generated by cf-ips.sh on $(date -u +%FT%TZ). Do not edit."
  for c in $V4 $V6; do echo "set_real_ip_from $c;"; done
  echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"
install -m 0644 "$tmp" "$out"; rm -f "$tmp"

for c in $V4 $V6; do
  ufw allow proto tcp from "$c" to any port 443 comment 'cloudflare' >/dev/null
done

nginx -t -q && systemctl reload nginx
echo "cloudflare ranges: $(echo $V4 | wc -w) v4, $(echo $V6 | wc -w) v6"
# Ranges Cloudflare removes are not pruned from ufw automatically; that happens rarely.
# To prune: `ufw status numbered | grep cloudflare`, delete the stale ones, re-run this.
